### ISSUE TITLE
Update NetCoreControls to 1.0.0-beta2

### ISSUE THREAD

**Issue by AngryShaDoW** [ByteNuts/NetCoreControls.Samples#1]
It would be nice to update the version of the library

**Comment by jrcpereira** [comment]
Done!
Sorry for the delay...

The **master** branch contains the latest NuGet package (at the moment 1.0.0-beta2).

Added the **dev** branch that contains the latest MyGet package (which is build in every master commit and contains your pull request).

Thanks!
